function(luna_add_editor_native_plugin)
    set(options)
    set(one_value_args TARGET OUTPUT_NAME PACKAGE_DIR PLATFORM_DIR)
    set(multi_value_args SOURCES)
    cmake_parse_arguments(LUNA_EDITOR_PLUGIN "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

    if(LUNA_EDITOR_PLUGIN_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "luna_add_editor_native_plugin received unknown arguments: ${LUNA_EDITOR_PLUGIN_UNPARSED_ARGUMENTS}")
    endif()

    if(NOT LUNA_EDITOR_PLUGIN_TARGET)
        message(FATAL_ERROR "luna_add_editor_native_plugin requires TARGET")
    endif()

    if(NOT LUNA_EDITOR_PLUGIN_SOURCES)
        message(FATAL_ERROR "luna_add_editor_native_plugin requires SOURCES")
    endif()

    if(NOT LUNA_EDITOR_PLUGIN_OUTPUT_NAME)
        set(LUNA_EDITOR_PLUGIN_OUTPUT_NAME "${LUNA_EDITOR_PLUGIN_TARGET}")
    endif()

    if(NOT LUNA_EDITOR_PLUGIN_PACKAGE_DIR)
        set(LUNA_EDITOR_PLUGIN_PACKAGE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    endif()

    if(NOT LUNA_EDITOR_PLUGIN_PLATFORM_DIR)
        if(WIN32)
            set(LUNA_EDITOR_PLUGIN_PLATFORM_DIR Win64)
        elseif(APPLE)
            set(LUNA_EDITOR_PLUGIN_PLATFORM_DIR macOS)
        else()
            set(LUNA_EDITOR_PLUGIN_PLATFORM_DIR Linux)
        endif()
    endif()

    if(WIN32)
        set(LUNA_EDITOR_PLUGIN_PREFIX "")
    else()
        set(LUNA_EDITOR_PLUGIN_PREFIX "lib")
    endif()

    set(LUNA_EDITOR_PLUGIN_OUTPUT_DIR
        "${LUNA_EDITOR_PLUGIN_PACKAGE_DIR}/Binaries/${LUNA_EDITOR_PLUGIN_PLATFORM_DIR}"
    )

    add_library(${LUNA_EDITOR_PLUGIN_TARGET} SHARED ${LUNA_EDITOR_PLUGIN_SOURCES})
    target_compile_features(${LUNA_EDITOR_PLUGIN_TARGET} PRIVATE cxx_std_20)
    target_link_libraries(${LUNA_EDITOR_PLUGIN_TARGET} PRIVATE Luna::EditorSDK)

    set_target_properties(
        ${LUNA_EDITOR_PLUGIN_TARGET}
        PROPERTIES
            OUTPUT_NAME "${LUNA_EDITOR_PLUGIN_OUTPUT_NAME}"
            PREFIX "${LUNA_EDITOR_PLUGIN_PREFIX}"
            RUNTIME_OUTPUT_DIRECTORY "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
            RUNTIME_OUTPUT_DIRECTORY_DEBUG "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
            RUNTIME_OUTPUT_DIRECTORY_RELEASE "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
            RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
            RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
            LIBRARY_OUTPUT_DIRECTORY "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
            LIBRARY_OUTPUT_DIRECTORY_DEBUG "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
            LIBRARY_OUTPUT_DIRECTORY_RELEASE "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
            LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
            LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
            ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
            ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_BINARY_DIR}"
            ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_BINARY_DIR}"
            ARCHIVE_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_CURRENT_BINARY_DIR}"
            ARCHIVE_OUTPUT_DIRECTORY_MINSIZEREL "${CMAKE_CURRENT_BINARY_DIR}"
    )

    set(${LUNA_EDITOR_PLUGIN_TARGET}_LUNA_EDITOR_PLUGIN_PLATFORM_DIR
        "${LUNA_EDITOR_PLUGIN_PLATFORM_DIR}"
        PARENT_SCOPE
    )
    set(${LUNA_EDITOR_PLUGIN_TARGET}_LUNA_EDITOR_PLUGIN_OUTPUT_DIR
        "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
        PARENT_SCOPE
    )
endfunction()
