cmake_minimum_required(VERSION 3.16)
project(LunaEditorNativePluginTemplate LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

find_package(LunaEditorSDK CONFIG REQUIRED)

add_library(
    LunaEditorNativePluginTemplate
    SHARED
    Source/NativeTemplatePlugin.cpp
)

target_link_libraries(
    LunaEditorNativePluginTemplate
    PRIVATE
        Luna::EditorSDK
)

if(WIN32)
    set(LUNA_EDITOR_PLUGIN_PLATFORM_DIR Win64)
    set(LUNA_EDITOR_PLUGIN_PREFIX "")
elseif(APPLE)
    set(LUNA_EDITOR_PLUGIN_PLATFORM_DIR macOS)
    set(LUNA_EDITOR_PLUGIN_PREFIX "lib")
else()
    set(LUNA_EDITOR_PLUGIN_PLATFORM_DIR Linux)
    set(LUNA_EDITOR_PLUGIN_PREFIX "lib")
endif()

set(LUNA_EDITOR_PLUGIN_OUTPUT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Binaries/${LUNA_EDITOR_PLUGIN_PLATFORM_DIR}")

set_target_properties(
    LunaEditorNativePluginTemplate
    PROPERTIES
        OUTPUT_NAME "LunaEditorNativePluginTemplate"
        PREFIX "${LUNA_EDITOR_PLUGIN_PREFIX}"
        RUNTIME_OUTPUT_DIRECTORY "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
        RUNTIME_OUTPUT_DIRECTORY_DEBUG "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
        RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
        RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY_DEBUG "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY_RELEASE "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL "${LUNA_EDITOR_PLUGIN_OUTPUT_DIR}"
)
