cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED LUNA_BINARY_DIR OR LUNA_BINARY_DIR STREQUAL "")
    message(FATAL_ERROR "LUNA_BINARY_DIR is required")
endif()

if(NOT DEFINED LUNA_SDK_CONTRACT_ROOT OR LUNA_SDK_CONTRACT_ROOT STREQUAL "")
    message(FATAL_ERROR "LUNA_SDK_CONTRACT_ROOT is required")
endif()

if(NOT DEFINED LUNA_TEST_CONFIGURATION OR LUNA_TEST_CONFIGURATION STREQUAL "")
    set(LUNA_TEST_CONFIGURATION Debug)
endif()

get_filename_component(LUNA_BINARY_DIR_ABS "${LUNA_BINARY_DIR}" ABSOLUTE)
get_filename_component(LUNA_SDK_CONTRACT_ROOT_ABS "${LUNA_SDK_CONTRACT_ROOT}" ABSOLUTE)

file(TO_CMAKE_PATH "${LUNA_BINARY_DIR_ABS}" LUNA_BINARY_DIR_NORM)
file(TO_CMAKE_PATH "${LUNA_SDK_CONTRACT_ROOT_ABS}" LUNA_SDK_CONTRACT_ROOT_NORM)

string(FIND "${LUNA_SDK_CONTRACT_ROOT_NORM}" "${LUNA_BINARY_DIR_NORM}" LUNA_CONTRACT_ROOT_IN_BUILD)
if(NOT LUNA_CONTRACT_ROOT_IN_BUILD EQUAL 0)
    message(FATAL_ERROR "Refusing to use SDK contract root outside the build tree: ${LUNA_SDK_CONTRACT_ROOT_ABS}")
endif()

set(LUNA_SDK_INSTALL_DIR "${LUNA_SDK_CONTRACT_ROOT_ABS}/install")
set(LUNA_SDK_TEMPLATE_BUILD_DIR "${LUNA_SDK_CONTRACT_ROOT_ABS}/template-build")

file(REMOVE_RECURSE "${LUNA_SDK_INSTALL_DIR}" "${LUNA_SDK_TEMPLATE_BUILD_DIR}")
file(MAKE_DIRECTORY "${LUNA_SDK_CONTRACT_ROOT_ABS}")

execute_process(
    COMMAND
        "${CMAKE_COMMAND}"
        --install "${LUNA_BINARY_DIR_ABS}"
        --config "${LUNA_TEST_CONFIGURATION}"
        --prefix "${LUNA_SDK_INSTALL_DIR}"
        --component LunaEditorSDK
    RESULT_VARIABLE LUNA_SDK_INSTALL_RESULT
    OUTPUT_VARIABLE LUNA_SDK_INSTALL_OUTPUT
    ERROR_VARIABLE LUNA_SDK_INSTALL_ERROR
)

if(NOT LUNA_SDK_INSTALL_RESULT EQUAL 0)
    message(FATAL_ERROR "Failed to install LunaEditorSDK component.\n${LUNA_SDK_INSTALL_OUTPUT}\n${LUNA_SDK_INSTALL_ERROR}")
endif()

set(LUNA_SDK_TEMPLATE_SOURCE_DIR "${LUNA_SDK_INSTALL_DIR}/share/LunaEditorSDK/Templates/NativePlugin")
if(NOT EXISTS "${LUNA_SDK_TEMPLATE_SOURCE_DIR}/CMakeLists.txt")
    message(FATAL_ERROR "Installed SDK native template is missing: ${LUNA_SDK_TEMPLATE_SOURCE_DIR}")
endif()
if(NOT EXISTS "${LUNA_SDK_TEMPLATE_SOURCE_DIR}/assets/welcome.txt")
    message(FATAL_ERROR "Installed SDK native template is missing assets/welcome.txt")
endif()

set(LUNA_TEMPLATE_CONFIGURE_ARGS
    -S "${LUNA_SDK_TEMPLATE_SOURCE_DIR}"
    -B "${LUNA_SDK_TEMPLATE_BUILD_DIR}"
    "-DCMAKE_PREFIX_PATH=${LUNA_SDK_INSTALL_DIR}"
)

if(DEFINED LUNA_CMAKE_GENERATOR AND NOT LUNA_CMAKE_GENERATOR STREQUAL "")
    list(APPEND LUNA_TEMPLATE_CONFIGURE_ARGS -G "${LUNA_CMAKE_GENERATOR}")
endif()

if(DEFINED LUNA_CMAKE_GENERATOR_PLATFORM AND NOT LUNA_CMAKE_GENERATOR_PLATFORM STREQUAL "")
    list(APPEND LUNA_TEMPLATE_CONFIGURE_ARGS -A "${LUNA_CMAKE_GENERATOR_PLATFORM}")
endif()

if(DEFINED LUNA_CMAKE_GENERATOR_TOOLSET AND NOT LUNA_CMAKE_GENERATOR_TOOLSET STREQUAL "")
    list(APPEND LUNA_TEMPLATE_CONFIGURE_ARGS -T "${LUNA_CMAKE_GENERATOR_TOOLSET}")
endif()

execute_process(
    COMMAND "${CMAKE_COMMAND}" ${LUNA_TEMPLATE_CONFIGURE_ARGS}
    RESULT_VARIABLE LUNA_TEMPLATE_CONFIGURE_RESULT
    OUTPUT_VARIABLE LUNA_TEMPLATE_CONFIGURE_OUTPUT
    ERROR_VARIABLE LUNA_TEMPLATE_CONFIGURE_ERROR
)

if(NOT LUNA_TEMPLATE_CONFIGURE_RESULT EQUAL 0)
    message(FATAL_ERROR "Failed to configure SDK native template.\n${LUNA_TEMPLATE_CONFIGURE_OUTPUT}\n${LUNA_TEMPLATE_CONFIGURE_ERROR}")
endif()

execute_process(
    COMMAND
        "${CMAKE_COMMAND}"
        --build "${LUNA_SDK_TEMPLATE_BUILD_DIR}"
        --config "${LUNA_TEST_CONFIGURATION}"
    RESULT_VARIABLE LUNA_TEMPLATE_BUILD_RESULT
    OUTPUT_VARIABLE LUNA_TEMPLATE_BUILD_OUTPUT
    ERROR_VARIABLE LUNA_TEMPLATE_BUILD_ERROR
)

if(NOT LUNA_TEMPLATE_BUILD_RESULT EQUAL 0)
    message(FATAL_ERROR "Failed to build SDK native template.\n${LUNA_TEMPLATE_BUILD_OUTPUT}\n${LUNA_TEMPLATE_BUILD_ERROR}")
endif()

message(STATUS "LunaEditorSDK native template contract passed")
