if(TARGET LunaEditor)
    add_subdirectory(AssetLoading)
    add_subdirectory(BackendCapabilities)
    add_subdirectory(BuiltinMaterials)
    add_subdirectory(ContentBrowser)
    add_subdirectory(CoreCommands)
    add_subdirectory(EditorApiSample)
    add_subdirectory(Inspector)
    add_subdirectory(PluginManager)
    add_subdirectory(RenderDebug)
    add_subdirectory(RenderFeatures)
    add_subdirectory(RenderProfiler)
    add_subdirectory(SceneHierarchy)
    add_subdirectory(SceneSettings)
    add_subdirectory(SceneStatus)
    add_subdirectory(ScriptPlugins)
    add_subdirectory(Viewport)
endif()
