#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer IndirectArgs
{
    uint groupCountX;
    uint groupCountY;
    uint groupCountZ;
} argsBuffer;

layout(push_constant) uniform GenerateArgsParams
{
    uvec4 requested;
} PushConstants;

void main()
{
    argsBuffer.groupCountX = max(PushConstants.requested.x, 1u);
    argsBuffer.groupCountY = max(PushConstants.requested.y, 1u);
    argsBuffer.groupCountZ = 1u;
}
