add_library(
    LunaEditorNativeSample
    SHARED
    Source/NativeSampleEditorPlugin.cpp
)

target_link_libraries(
    LunaEditorNativeSample
    PRIVATE
        LunaEditorSDK
)

if(WIN32)
    set(LUNA_EDITOR_NATIVE_SAMPLE_PLATFORM_DIR Win64)
    set(LUNA_EDITOR_NATIVE_SAMPLE_PREFIX "")
elseif(APPLE)
    set(LUNA_EDITOR_NATIVE_SAMPLE_PLATFORM_DIR macOS)
    set(LUNA_EDITOR_NATIVE_SAMPLE_PREFIX "lib")
else()
    set(LUNA_EDITOR_NATIVE_SAMPLE_PLATFORM_DIR Linux)
    set(LUNA_EDITOR_NATIVE_SAMPLE_PREFIX "lib")
endif()

set(LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Binaries/${LUNA_EDITOR_NATIVE_SAMPLE_PLATFORM_DIR}")

set_target_properties(
    LunaEditorNativeSample
    PROPERTIES
        OUTPUT_NAME "LunaEditorNativeSample"
        PREFIX "${LUNA_EDITOR_NATIVE_SAMPLE_PREFIX}"
        RUNTIME_OUTPUT_DIRECTORY "${LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR}"
        RUNTIME_OUTPUT_DIRECTORY_DEBUG "${LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR}"
        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR}"
        RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR}"
        RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY "${LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY_DEBUG "${LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY_RELEASE "${LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY_RELWITHDEBINFO "${LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR}"
        LIBRARY_OUTPUT_DIRECTORY_MINSIZEREL "${LUNA_EDITOR_NATIVE_SAMPLE_OUTPUT_DIR}"
)

if(TARGET LunaEditor)
    add_dependencies(LunaEditor LunaEditorNativeSample)
endif()
